library(caret)
context('Test Data Splitting Functions')

test_that('createTimeSlices', {
  set.seed(1)
  y <- 1:10

  s1 <- createTimeSlices(y, initialWindow=5, horizon=1, fixedWindow=TRUE)
  expect_equal(length(s1$train), 5)
  expect_equal(length(s1$test), 5)
  expect_equal(s1$train$Training1, 1:5)
  expect_equal(s1$train$Training2, 2:6)
  expect_equal(s1$train$Training3, 3:7)
  expect_equal(s1$train$Training4, 4:8)
  expect_equal(s1$train$Training5, 5:9)
  expect_equal(s1$test$Testing1, 6)
  expect_equal(s1$test$Testing2, 7)
  expect_equal(s1$test$Testing3, 8)
  expect_equal(s1$test$Testing4, 9)
  expect_equal(s1$test$Testing5, 10)

  s2 <- createTimeSlices(y, initialWindow=5, horizon=1, fixedWindow=FALSE)
  expect_equal(length(s2$train), 5)
  expect_equal(length(s2$test), 5)
  expect_equal(s2$train$Training1, 1:5)
  expect_equal(s2$train$Training2, 1:6)
  expect_equal(s2$train$Training3, 1:7)
  expect_equal(s2$train$Training4, 1:8)
  expect_equal(s2$train$Training5, 1:9)
  expect_equal(s2$test$Testing1, 6)
  expect_equal(s2$test$Testing2, 7)
  expect_equal(s2$test$Testing3, 8)
  expect_equal(s2$test$Testing4, 9)
  expect_equal(s2$test$Testing5, 10)

  s3 <- createTimeSlices(y, initialWindow=5, horizon=5, fixedWindow=TRUE)
  expect_equal(length(s3$train), 1)
  expect_equal(length(s3$test), 1)
  expect_equal(s3$train$Training1, 1:5)
  expect_equal(s3$test$Testing1, 6:10)

  s4 <- createTimeSlices(y, initialWindow=5, horizon=5, fixedWindow=FALSE)
  expect_equal(length(s3$train), 1)
  expect_equal(length(s3$test), 1)
  expect_equal(s3$train$Training1, 1:5)
  expect_equal(s3$test$Testing1, 6:10)

  expect_identical(s3, s4)
})
